# Generated by Django 2.0.3 on 2018-03-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('success', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamSeesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examID', models.CharField(db_index=True, max_length=50)),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата экзамена')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.AnswerModel')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'exam_items',
            },
        ),
        migrations.CreateModel(
            name='QuestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Вопрос №: ', max_length=7, verbose_name='Номер теста')),
                ('quest', models.TextField(verbose_name='Вопрос')),
                ('toExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='tests.ExamModel', verbose_name='Тест')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'Quets',
            },
        ),
        migrations.AddField(
            model_name='examseesion',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.QuestModel'),
        ),
        migrations.AddField(
            model_name='examseesion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='toQuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.QuestModel', verbose_name='Ответ'),
        ),
    ]
