# Generated by Django 2.0.3 on 2018-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_exammodel_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='countQuest',
            field=models.IntegerField(default=0, verbose_name='Число вопросов'),
        ),
    ]
