# Generated by Django 2.0.3 on 2018-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_exammodel_countquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questmodel',
            name='successAsnwers',
            field=models.CharField(blank=True, max_length=20, verbose_name='Правильные ответы'),
        ),
    ]
