# Generated by Django 2.0.3 on 2018-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_answermodel_id_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='id_answer',
            field=models.IntegerField(default=0, verbose_name='ID ответа'),
        ),
    ]
