# Generated by Django 2.0.3 on 2018-04-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20180405_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='id_answer',
        ),
    ]
