# Generated by Django 2.0.3 on 2018-03-12 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180312_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedmodel',
            name='toExams',
            field=models.ManyToManyField(blank=True, related_name='toExams', to='tests.ExamModel', verbose_name='Тесты пользователя'),
        ),
        migrations.AlterField(
            model_name='userextendedmodel',
            name='toUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ext_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
