# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'ExamNotarius' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.7'
  pod 'CodableAlamofire', '~> 1.1'
  pod 'KeychainSwift', '~> 10.0'
  pod 'RealmSwift', '~> 3.2'
  pod 'TextFieldEffects', '~> 1.4'
end
